Shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from .views import BaseView, ProductDetailView, CategoryDetailView

urlpatterns = [
    path('', BaseView.as_view(), name='base'),
    path('products/<str:ct_model>/<str:slug>/', ProductDetailView.as_view(), name='product_detail'),
    path('category/<str:slug>/', CategoryDetailView.as_view(), name='category_detail'),
]

mainapp/models.py
from PIL import Image
# from io import BytesIO
# import sys

from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.urls import reverse
# from django.core.files.uploadedfile import InMemoryUploadedFile

User = get_user_model()


def get_models_for_count(*model_names):
    return ([models.Count(model_name) for model_name in model_names])


def get_product_url(obj, viewname):
    ct_model = obj.__class__._meta.model_name
    return reverse(viewname, kwargs={'ct-model': ct_model, 'slug': obj.slug})


class MinResolutionErrorException(Exception):
    pass


class MaxResolutionErrorException(Exception):
    pass


class LatestProductsManager:

    @staticmethod
    def get_products_for_main_page(*args, **kwargs):
        with_respect_to = kwargs.get('with_respect_to')
        products = []
        ct_models = ContentType.objects.filter(model__in=args)
        for ct_model in ct_models:
            model_products = ct_model.model_class()._base_manager.all().order_by('-id')[:5]
            products.extend(model_products)

        if with_respect_to:
            ct_model = ContentType.objects.filter(model=with_respect_to)
            if ct_model.exists():
                if with_respect_to in args:
                    return sorted(products,
                                  key=lambda x: x.__class__._meta.model_name.startswith(with_respect_to),
                                  reverse=True)

        return products


class LatestProducts:

    objects = LatestProductsManager()



class CategoryManager(models.Manager):

    CATEGORY_NAME_COUNT_NAME = {
        'Ноутбуки': 'notebook__count',
        'Смартфоны': 'smartphone__count'
    }

    def get_queryset(self):
        return super().get_queryset()

    def get_categories_for_left_sidebar(self):
        models = get_models_for_count('notebook', 'smartphone')
        qs = list(self.get_queryset().annotate(*models))
        data = [
            dict(name=c.name, url=c.get_absolute_url(), count=getattr(c, self.CATEGORY_NAME_COUNT_NAME[c.name])) for c in qs
        ]
        return data



class Category(models.Model):

    name = models.CharField(max_length=255, verbose_name='Имя категории')
    slug = models.SlugField(unique=True)
    objects = CategoryManager()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'slug': self.slug})


class Product(models.Model):

    MIN_RESOLUTION = (400, 400)
    MAX_RESOLUTION = (4000, 4000)
    MAX_IMAGE_SIZE = 31457285

    class Meta:
        abstract = True

    category = models.ForeignKey(Category, verbose_name='Категория', on_delete=models.CASCADE)
    title = models.CharField(max_length=255, verbose_name='Наименование')
    slug = models.SlugField(unique=True)
    image = models.ImageField(verbose_name='Изображение')
    description = models.TextField(verbose_name='Описание', null=True)
    price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Цена')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        image = self.image
        img = Image.open(image)

        min_height, min_width = self.MIN_RESOLUTION
        max_height, max_width = self.MAX_RESOLUTION

        if img.height < min_height or img.width < min_width:
            raise MinResolutionErrorException("Разрешение изображения меньше минимального!")
        if img.height > max_height or img.width > max_width:
            raise MaxResolutionErrorException("Разрешение изображения больше максимального!")
        # image = self.image
        # img = Image.open(image)
        # new_img = img.convert("RGB")
        # resized_new_img = new_img.resize((200,200), Image.HAMMING)
        # filestream = BytesIO()
        # resized_new_img.save(filestream, 'JPEG', quality=90)
        # filestream.seek(0)
        # name = '{}.{}'.format(*self.image.name.split('.'))
        # self.image = InMemoryUploadedFile(filestream, 'ImageField', name, 'jpeg/image', sys.getsizeof(filestream), None)
        super().save(*args, **kwargs)


class Notebook(Product):

    diagonal = models.CharField(max_length=255, verbose_name='Диагональ')
    display_type = models.CharField(max_length=255, verbose_name='Тип дисплея')
    processor_freq = models.CharField(max_length=255, verbose_name='Частота процессора')
    ram = models.CharField(max_length=255, verbose_name='Оперативная память')
    video = models.CharField(max_length=255, verbose_name='Видеокарта')
    time_without_charge = models.CharField(max_length=255, verbose_name='Время работы от аккумулятора')

    def __str__(self):
        return "{} : {}".format(self.category.name, self.title)

    def get_absolute_url(self):
        return get_product_url(self, 'product_detail')
    # def get_absolute_url(self):
    #     return reverse('product_detail', kwargs={'ct-model': 'notebook', 'slug': self.slug})

class Smartphone(Product):
    diagonal = models.CharField(max_length=255, verbose_name='Диагональ')
    display_type = models.CharField(max_length=255, verbose_name='Тим дисплея')
    resolution = models.CharField(max_length=255, verbose_name='Разрешение экрана')
    accum_volume = models.CharField(max_length=255, verbose_name='Объем батареи')
    ram = models.CharField(max_length=255, verbose_name='Оперативная память')
    sd = models.BooleanField(default=True, verbose_name='Наличие SD карты')
    sd_volume_max = models.CharField(max_length=255, null=True, blank=True, verbose_name='Максимальный объем встраиваемой памяти')
    main_cam_mp = models.CharField(max_length=255, verbose_name='Главнеая камера')
    frontal_cam_mp = models.CharField(max_length=255, verbose_name='Фронтальная камера')

    def __str__(self):
        return "{} : {}".format(self.category.name, self.title)

    def get_absolute_url(self):
        return get_product_url(self, 'product_detail')
    # def get_absolute_url(self):
    #     return reverse('product_detail', kwargs={'ct-model': 'smartphone', 'slug': self.slug})


    # @property
    # def sd(self):
    #     if self.sd:
    #         return 'Да'
    #     return 'Нет'


class CartProduct(models.Model):

    user = models.ForeignKey('Customer', verbose_name='Покупатель', on_delete=models.CASCADE)
    cart = models.ForeignKey('Cart', verbose_name='Корзина', on_delete=models.CASCADE, related_name='related_products')
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    qty = models.PositiveIntegerField(default=1)
    final_price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Общая цена')

    def __str__(self):
        return "Продукт:  {} (для корзины)".format(self.content_object.title)


class Cart(models.Model):

    owner = models.ForeignKey('Customer', verbose_name='Владелец', on_delete=models.CASCADE)
    products = models.ManyToManyField(CartProduct, blank=True, related_name='related_cart')
    total_products = models.PositiveIntegerField(default=0)
    final_price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Общая цена')
    in_order = models.BooleanField(default=False)
    for_anonymous_user = models.BooleanField(default=False)

    def __str__(self):
        return str(self.id)


class Customer(models.Model):

    user = models.ForeignKey(User, verbose_name="ПОльзователь", on_delete=models.CASCADE)
    phone = models.CharField(max_length=20, verbose_name='Номрер телефона')
    address = models.CharField(max_length=255, verbose_name='Адрес')

    def __str__(self):
        return "Покупатель: {} {}".format(self.user.first_name, self.user.last_name)

mainapp/views.py
from django.shortcuts import render
from django.views.generic import DetailView, View

from .models import Notebook, Smartphone, Category, LatestProducts
from .mixins import CategoryDetailMixin


class BaseView(View):

    def get(self, request, *args, **kwargs):
        categories = Category.objects.get_categories_for_left_sidebar()
        products = LatestProducts.objects.get_products_for_main_page(
            'notebook', 'smartphone'
        )
        context = {
            'categories': categories,
            'products': products
        }
        return render(request, 'base.html', context)



class ProductDetailView(CategoryDetailMixin, DetailView):

    CT_MODEL_MODEL_CLASS = {
        'notebook': Notebook,
        'smartphone': Smartphone
    }

    def dispatch(self, request, *args, **kwargs):
        self.model = self.CT_MODEL_MODEL_CLASS[kwargs['ct_model']]
        self.queryset = self.model._base_manager.all()
        return super().dispatch(request, *args, *kwargs)
    # model = Model
    # queryset = Model.objects.all()
    context_object_name = 'product'
    template_name = 'product_detail.html'
    slug_url_kwarg = 'slug'


class CategoryDetailView(CategoryDetailMixin, DetailView):

    model = Category
    queryset = Category.objects.all()
    context_object_name = 'category'
    template_name = 'category_detail.html'
    slug_url_kwarg = 'slug'

mainapp/templates/admin.html
{% extends 'admin/change_form.html' %}
{% load static %}

{% block admin_change_form_document_ready %}
    {{ block.super }}
    <script>
        (function($) {
            $('#id_sd').on('click', function(){
                if($('#id_sd').prop('checked') == true){
                    $('#id_sd_volume_max').prop('readonly', false)
                    $('#id_sd_volume_max').val('')
                    $('#id_sd_volume_max').css('background', 'white')
                }else{
                    $('#id_sd_volume_max').prop('readonly', true)
                    $('#id_sd_volume_max').val('')
                    $('#id_sd_volume_max').css('background', 'lightgrey')
                }
            })
        })(django.jQuery);
    </script>
{% endblock %}

mainapp/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Shop Homepage - Start Bootstrap Template</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="css/shop-homepage.css" rel="stylesheet">

</head>

<style>
    body {
        padding-top: 56px;
    }
</style>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="#">Start Bootstrap</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Services</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Contact</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<!-- Page Content -->
<div class="container">

    <div class="row">

        <div class="col-lg-3">

            <h1 class="my-4">Dan4i shop</h1>
            <div class="list-group">
                {% for category in categories %}
                    <a href="{{ category.url }}" class="list-group-item">{{category.name}} ({{ category.count }})</a>
                {% endfor %}


            </div>

        </div>
        <!-- /.col-lg-3 -->

        <div class="col-lg-9">
            {% block content %}

                <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner" role="listbox">
                        <div class="carousel-item active">
                            <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="First slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Second slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Third slide">
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>

                <div class="row">
                    {% for product in products %}
                        <div class="col-lg-4 col-md-6 mb-4">
                            <div class="card h-100">
                                <a href="{{ product.get_absolute_url }}"><img class="card-img-top" src="{{ product.image.url}}" alt=""></a>
                                <div class="card-body">
                                    <h4 class="card-title">
                                        <a href="{{ product.get_absolute_url }}">{{product.title}}</a>
                                    </h4>
                                    <h5>{{ product.price}} грн.</h5>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <!-- /.row -->
            {% endblock content %}
        </div>
        <!-- /.col-lg-9 -->

    </div>
    <!-- /.row -->

</div>
<!-- /.container -->

<!-- Footer -->
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Dan4i shop 2020</p>
    </div>
    <!-- /.container -->
</footer>

<!-- Bootstrap core JavaScript -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</body>

</html>

mainapp/templates/category_detail.html
{%  extends 'base.html' %}


{% block content %}

    {{ category.name }}

{% endblock %}

mainapp/templates/notebook_specification.html
<table class="table">
    <tbody>
    <tr>
        <td>Диагональ</td>
        <td>{{ product.diagonal }}</td>
    </tr>
    <tr>
        <td>Тип дисплея</td>
        <td>{{ product.display_type }}</td>
    </tr>
    <tr>
        <td>Частота процессора</td>
        <td>{{ product.processor_freq }}</td>
    </tr>
    <tr>
        <td>Оперативная память</td>
        <td>{{ product.ram }}</td>
    </tr>
    <tr>
        <td>Видеокарта</td>
        <td>{{ product.video }}</td>
    </tr>
    <tr>
        <td>Время работы от аккумулятора</td>
        <td>{{ product.time_without_charge }}</td>
    </tr>
    </tbody>
</table>

mainapp/templates/product_detail.html
{% extends 'base.html' %}
{% load specifications %}

{% block content %}
    <nav aria-label="breadcrumb" class="mt-3">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'base' %}">Главная</a></li>
            <li class="breadcrumb-item"><a href="#">{{product.category.name}}</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{product.title}}</li>
        </ol>
    </nav>

    <div class="row">
        <div class="col-md-4">
            <img src="{{ product.image.url }}" class="img-fluid" alt="">
        </div>
        <div class="col-md-8">
            <h3>{{ product.title }}</h3>
            <p>Цена: {{ product.price }} грн.</p>
            <p>Описание: {{ product.description }}</p>
        </div>
        <p class="mt-4">Характеристики: </p>

        {{  product|product_spec }}

{#        {% if product.category.slug == 'notebooks' %}#}
{#            {% include 'notebook_specification.html' %}#}
{#        {%  else %}#}
{#            {% include 'smartphone_specification.html' %}#}
{#        {% endif %}#}


    </div>


{% endblock content %}

mainapp/templates/smartphone_specification.html
<table class="table">
    <tbody>
    <tr>
        <td>Диагональ</td>
        <td>{{ product.diagonal }}</td>
    </tr>
    <tr>
        <td>Тип дисплея</td>
        <td>{{ product.display_type }}</td>
    </tr>
    <tr>
        <td>Разрешение экрана</td>
        <td>{{ product.resolution }}</td>
    </tr>
    <tr>
        <td>Заряд аккумулятора</td>
        <td>{{ product.accum_volume }}</td>
    </tr>
    <tr>
        <td>Оперативная память</td>
        <td>{{ product.ram }}</td>
    </tr>
    <tr>
        <td>Наличие слота для SD карты</td>
        <td>{{ product.sd }}</td>
    </tr>
    <tr>
        <td>Максимальный объем SD карты</td>
        <td>{{ product.sd_volume_max }}</td>
    </tr>
    <tr>
        <td>Камера (МП)</td>
        <td>{{ product.main_cam_mp }}</td>
    </tr>
    <tr>
        <td>Фронтальная камера (МП)</td>
        <td>{{ product.frontal_cam_mp }}</td>
    </tr>
    </tbody>
</table>